### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by Kakemixen** [mjukvarelauget/SlightlyInstrusiveSitater#1]
## Expected Behavior
I'd like to see quotes in polybar

## Actual Behavior
I can't see quotes in polybar. 
This is highly likely because a lot of colours is hard to se on some backgrounds (in this case yellow).

![image-for-show](https://i.imgur.com/zIl4T94.png)

I'd like to be able to choose colours myself, please.

## Steps to Reproduce the Problem

  1. Follow how-to
  2. run with yellow background
  3. squint

## Specifications

  - Version: 0.1.0
  - Platform: 5.2.11-1-MANJARO

**Comment by JoakimOL** [comment]
Interesting. There are default threshold values, meant to avoid awkward colors - but this is assuming you are a human being using a sensible background color.

Would it be sufficient to add an argument to set a color, effectively disabling the random color generation?

Open for suggestions

**Comment by Kakemixen** [comment]
You could give it as a parameter, but if you want to follow a colourscheme, you would need to feed the colour-value multiple times. 

I would prefer a solution using no colours at all, thus defaulting to the colourscheme of the bar in use. I believe this solution would also simplify the application.

**Comment by JoakimOL** [comment]
Implemented in 6e3d362

This commit adds two new flags:

- `-c "<6-character hex color>` to set the text color by hand
- `-n` to disable color tags generation

Closing for now, let me know and reopen if it's not satisfactory
